"""initial schema

Revision ID: 5ff0171a2d71
Revises: 
Create Date: 2026-09-04 16:38:50.651508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ff0171a2d71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('work_model', sa.Enum('REMOTE', 'HYBRID', 'ONSITE', name='work_model'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('direct_application_url', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experience_requirement', sa.Text(), nullable=False),
    sa.Column('language_requirements', sa.Text(), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', name='employment_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'EXPIRED', name='job_status'), nullable=False),
    sa.Column('role_family', sa.Text(), nullable=False),
    sa.Column('company_type', sa.Enum('PRODUCT', 'CONSULTANCY', name='company_type'), nullable=False),
    sa.Column('seniority_level', sa.Enum('JUNIOR', 'MEDIOR', 'SENIOR', name='seniority_level'), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preference_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_type', sa.Enum('ROLE_FAMILY', 'TECHNOLOGY', 'DOMAIN', 'COMPANY_TYPE', 'SENIORITY', 'LOCATION', 'WORK_MODEL', name='feature_type'), nullable=False),
    sa.Column('feature_value', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Enum('OBSERVATION', 'WEAK', 'MEDIUM', 'STRONG', name='confidence'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_type', 'feature_value')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('LIKE', 'REJECT', 'SHORTLIST', 'APPLY', 'INTERVIEW', 'OFFER', name='feedback_action'), nullable=False),
    sa.Column('reason', sa.Enum('TOO_SENIOR', 'TOO_JUNIOR', 'CONSULTING', 'COMPANY', 'DOMAIN', 'COMPENSATION', 'LOCATION', 'TECHNOLOGY', 'ROLE_CONTENT', 'LANGUAGE', 'VISA', 'OTHER', name='reject_reason'), nullable=True),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_job_id_created_at', 'feedback', ['job_id', 'created_at'], unique=False)
    op.create_table('match_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('technical_fit', sa.Float(), nullable=False),
    sa.Column('demonstrated_evidence', sa.Float(), nullable=False),
    sa.Column('seniority_fit', sa.Float(), nullable=False),
    sa.Column('domain_fit', sa.Float(), nullable=False),
    sa.Column('infrastructure_fit', sa.Float(), nullable=False),
    sa.Column('location_fit', sa.Float(), nullable=False),
    sa.Column('language_fit', sa.Float(), nullable=False),
    sa.Column('career_direction_fit', sa.Float(), nullable=False),
    sa.Column('preference_fit', sa.Float(), nullable=False),
    sa.Column('freshness', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('top_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_scores')
    op.drop_index('ix_feedback_job_id_created_at', table_name='feedback')
    op.drop_table('feedback')
    op.drop_table('preference_signals')
    op.drop_table('jobs')
    # ### end Alembic commands ###
